# Just a test config file
detector geometry:
  [
    [0, 15, -0.5, 0.0, 0, 1, 0, 10],
    [1, 4, 0.5, 2.5, 0, 1, 1, 10],
    [1, 4, 6.5, 8.5, 0, 1, 2, 10],
    [1, 4, 12.5, 14.5, 0, 1, 3, 10],
    [1, 4, 18.5, 20.5, 0, 1, 4, 10],
    [4, 7, 3.5, 5.5, 0, 1, 5, 10],
    [4, 7, 9.5, 11.5, 0, 1, 6, 10],
    [4, 7, 15.5, 17.5, 0, 1, 7, 10],
    [4, 7, 21.5, 23.5, 0, 1, 8, 10],
    [7, 10, 0.5, 2.5, 0, 1, 9, 10],
    [7, 10, 6.5, 10.5, 0, 1, 10, 10],
    [7, 10, 12.5, 14.5, 0, 1, 11, 10],
    [7, 10, 18.5, 20.5, 0, 1, 12, 10],
    [10, 13, 0.5, 2.5, 0, 1, 13, 10],
    [10, 13, 3.5, 5.5, 0, 1, 14, 10],
    [10, 13, 6.5, 8.5, 0, 1, 15, 10],
    [10, 13, 9.5, 11.5, 0, 1, 16, 10],
    [10, 13, 12.5, 14.5, 0, 1, 17, 10],
    [10, 13, 15.5, 17.5, 0, 1, 18, 10],
    [10, 13, 18.5, 20.5, 0, 1, 19, 10],
    [10, 13, 21.5, 23.5, 0, 1, 20, 10],
    [0, 15, 24.0, 24.5, 0, 1, 21, 10],
  ]
detector:
  crystal n subdivision xyz: [2, 2, 2]
  sensitive geometry indices:
    [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
  inner layer x up-lim: 8
image:
  dimension xyz: [7.0, 3.0, 1.0]
  voxel per mm xyz: [2.0, 2.0, 2.0]
  subdivision xyz: [1, 1, 1]
  detector x-shift: 50
  detector rotation: 0

Debug:
  Point A: [-40, -12.5, 0.5]
  Point B: [11.5, 13.5, 0.5]
